
- hosts: all
  remote_user: user
  tasks:
          # upload ssh key                
          - authorized_key:
                  user: alexandr
                  state: present
                  manage_dir: yes
                  key: "{{ lookup('file', '../id_rsa.pub') }}"
