- name: "adduser node_exporter"
  become: true
  become_user: root
  become_method: su
  hosts: "{{ var_host | default('none') }}"
  tasks:
  - name: create user
    user:
      name: node_exporter
      groups: node_exporter
      append: yes
      create_home: no
      shell: /sbin/nologin
      state: present
      comment: "Node_exporter nologin User"
  - name: Remove  package prometheus-node-exporter
    ansible.builtin.package:
      name: prometheus-node-exporter
      state: absent
  - name: copy items 
    ansible.builtin.copy:
      src: "{{item.src}}" 
      dest: "{{item.dest}}"
      owner: node_exporter
      group: node_exporter
      mode:  u=rwx,g=rwx,o=rx
      force: yes 
      
    with_items:
      - { src: '/home/user/ans/play/node_exporter/node_exporter.service', dest: '/etc/systemd/system/node_exporter.service' }
      - { src: '/home/user/ans/play/node_exporter/node_exporter', dest: '/usr/sbin/node_exporter' }
  
  - name: Make sure a service unit is running
    ansible.builtin.systemd:
      state: restarted
      force: yes
      masked: no
      enabled: yes
      daemon_reload: yes
      name: node_exporter
